// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// collect_diff_weight_cpp_dense
List collect_diff_weight_cpp_dense(NumericMatrix b12, NumericMatrix d12, NumericMatrix A, NumericMatrix B);
RcppExport SEXP _psF1pair_collect_diff_weight_cpp_dense(SEXP b12SEXP, SEXP d12SEXP, SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type b12(b12SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type d12(d12SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(collect_diff_weight_cpp_dense(b12, d12, A, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_psF1pair_collect_diff_weight_cpp_dense", (DL_FUNC) &_psF1pair_collect_diff_weight_cpp_dense, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_psF1pair(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
