# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collect_diff_weight_cpp_dense <- function(b12, d12, A, B) {
    .Call(`_psF1pair_collect_diff_weight_cpp_dense`, b12, d12, A, B)
}

